# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0013_auto_20161226_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=30)),
                ('password', models.CharField(default='123456', max_length=30)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.Student')),
            ],
        ),
    ]
