# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_classroom_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(to='university.Subject'),
        ),
    ]
