# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20160204_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='classSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='subjects',
        ),
        migrations.AddField(
            model_name='classsubjects',
            name='classroom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.Classroom'),
        ),
        migrations.AddField(
            model_name='classsubjects',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Term'),
        ),
        migrations.AddField(
            model_name='classsubjects',
            name='subjects',
            field=models.ManyToManyField(to='university.Subject'),
        ),
        migrations.AddField(
            model_name='classsubjects',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Year'),
        ),
    ]
