# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20160205_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubjects',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Classroom'),
        ),
    ]
