# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_auto_20160205_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DateOfBirth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
