# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_auto_20160206_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='examreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='examreport',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
