# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_auto_20160206_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
