# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_student_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Employee')),
            ],
        ),
    ]
