# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_auto_20161226_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='current_year',
        ),
        migrations.RemoveField(
            model_name='term',
            name='is_first',
        ),
        migrations.AddField(
            model_name='term',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='year',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
