# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_auto_20170130_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='level',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='level',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
