# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0015_auto_20170130_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='max_year',
        ),
        migrations.AddField(
            model_name='classroom',
            name='max_semesters',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default=4, max_length=10),
            preserve_default=False,
        ),
    ]
