# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0016_auto_20170130_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examreport',
            name='note',
            field=models.TextField(default=b'OK'),
        ),
    ]
