# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0018_auto_20170131_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='examreport',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.Term'),
        ),
    ]
