# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0019_examreport_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examreport',
            name='semester',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.Term'),
        ),
    ]
